In [7]:
import pandas as pd
import geopandas as gpd

In [63]:
df = pd.read_csv('../data/data.csv')

In [64]:
df.head()

    latitude  longitude                  close_date   close_price
0   1.501986  86.350685  2014-08-16 22:25:31.925431  1.302246e+06
1  36.367095 -98.664280  2014-08-05 06:34:00.165876  1.475045e+05
2  36.599284 -97.924700  2014-08-12 23:48:00.887510  1.374006e+05
3  67.994791  64.688589  2014-08-17 05:27:01.404296 -1.411200e+04
4  36.647982 -97.866100  2014-08-09 04:00:40.358242  2.391053e+05

In [65]:
# SAMPLE DIST CALCULATION WITH GEOPY

from geopy.distance import vincenty as geodistance

coord1 = (41.49008, -71.312796)

coord2 = (41.499498, -81.695391)

print(geodistance(coord1, coord2).kilometers)

866.455432901

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88042 entries, 0 to 88041
Data columns (total 4 columns):
latitude       88042 non-null float64
longitude      88042 non-null float64
close_date     88042 non-null object
close_price    88042 non-null float64
dtypes: float64(3), object(1)
memory usage: 2.7+ MB

#### It'd be easier to work with a Datetime object for close_date.

In [67]:
df.close_date = pd.DatetimeIndex(df.close_date)

In [68]:
# Given a home i, filter dataframe where closing date of neighbors > closing date i

# Take the first home as ex., which is iloc[0], you do.
sample_home_i = df.ix[df.close_date > df.iloc[0].close_date].copy()

In [69]:
coord = (df.iloc[0].latitude, df.iloc[0].longitude)

In [70]:
coord

(1.5019862274484983, 86.350684871581294)

In [75]:
df['lat_lon'] = zip(df.latitude, df.longitude)

In [81]:
coord2 = df.lat_lon[0]

In [82]:
coord1 = coord

In [83]:
geodistance(coord1, coord2)

Distance(0.0)

In [84]:
# Trying out apply func.
df.lat_lon.apply(lambda (coord2): geodistance(coord,coord2).miles)

0           0.000000
1        9805.171993
2        9794.639997
3        4699.419170
4        9791.691113
5        9796.819745
6        9827.770159
7        9790.622262
8        9784.951288
9        9803.542843
10       5968.415315
11       9810.278534
12       9816.775977
13       9798.695401
14       9817.868548
15       9812.658081
16       9816.091411
17       9803.686076
18       9797.139264
19       9789.515366
20       7238.974490
21       9797.279774
22       9785.743236
23       9834.009554
24       9811.311469
25       9762.551403
26       5314.803663
27       9803.787513
28       9790.256679
29       9795.699972
            ...
88012    9795.571929
88013    9801.364563
88014    9800.573966
88015    9795.622929
88016    9788.937426
88017    9790.638291
88018    9793.302462
88019    9794.952557
88020    9788.459135
88021    6732.763125
88022    9813.661813
88023    9808.603751
88024    9811.815053
88025    9813.444190
88026    9803.587789
88027    9815.318839
88028    1519.220263
88029    9817.784602
88030    9800.174703
88031    9804.416524
88032    9803.622284
88033    9802.704827
88034    9786.260412
88035    9796.194367
88036    9785.820432
88037    9820.230989
88038    9803.699058
88039    9801.796945
88040    9811.890242
88041    9824.651266
Name: lat_lon, dtype: float64

In [101]:
from model import preprocessing as pp

In [105]:
a = pp()

In [106]:
a._time_leakage(0)

In [107]:
a._distance()

In [108]:
a.df_home_i

,latitude,longitude,close_date,close_price,lat_lon,dist2home_i_miles
3,67.994791,64.688589,2014-08-17 05:27:01.404296,-1.411200e+04,"(67.9947909948, 64.6885894312)",0.000000
15,36.320807,-98.078240,2014-08-18 12:00:46.762896,6.828881e+04,"(36.320807, -98.07824)",5187.167293
18,36.554065,-98.013640,2014-08-18 09:40:19.255736,2.123790e+05,"(36.554065, -98.01364)",5170.775930
23,35.993674,-98.222600,2014-08-17 21:48:29.830210,1.508110e+05,"(35.993674, -98.2226)",5210.498631
30,36.191893,-98.708995,2014-08-19 05:10:00.711262,3.091153e+05,"(36.191893, -98.708995)",5199.978756
36,36.318313,-97.909570,2014-08-20 23:53:31.614603,5.157308e+04,"(36.318313, -97.90957)",5186.249840
40,35.899010,-101.043970,2014-08-25 00:51:15.023744,1.717561e+05,"(35.89901, -101.04397)",5233.552584
43,36.667098,-97.987840,2014-08-18 05:41:22.317197,2.049981e+05,"(36.667098, -97.98784)",5162.868257
44,36.148430,-98.389290,2014-08-18 12:14:05.836839,1.427638e+05,"(36.14843, -98.38929)",5200.956164
54,36.267203,-99.089016,2014-08-19 14:03:39.154284,9.474538e+04,"(36.267203, -99.089016)",5197.145678
55,36.322986,-98.538730,2014-08-20 23:41:31.597739,5.351159e+04,"(36.322986, -98.53873)",5189.936287
63,36.469310,-97.900900,2014-08-18 20:25:43.917061,2.493735e+05,"(36.46931, -97.9009)",5175.852809
66,36.086116,-98.606930,2014-08-18 10:40:32.083864,1.035668e+05,"(36.086116, -98.60693)",5206.591920
74,36.460387,-98.363840,2014-08-20 16:05:05.262521,1.646608e+05,"(36.460387, -98.36384)",5179.424053
87,36.239913,-98.665905,2014-08-18 12:22:10.004480,2.397236e+05,"(36.239913, -98.665905)",5196.420944
95,36.613303,-98.055835,2014-08-17 12:59:33.647655,2.201652e+05,"(36.613303, -98.055835)",5166.989638
100,36.424685,-98.576030,2014-08-21 23:22:35.599466,2.122132e+05,"(36.424685, -98.57603)",5183.201036
104,36.675000,-98.156410,2014-08-21 08:00:37.125225,2.281354e+05,"(36.675, -98.15641)",5163.406734
114,36.052360,-98.189720,2014-08-19 03:44:53.646681,3.275575e+05,"(36.05236, -98.18972)",5206.268723
117,36.137217,-98.328240,2014-08-20 14:12:08.749413,2.807137e+05,"(36.137217, -98.32824)",5201.337981
123,36.254958,-98.125660,2014-08-19 15:47:20.812602,3.160944e+05,"(36.254958, -98.12566)",5191.981677
124,36.691970,-98.049890,2014-08-17 17:54:04.423140,2.902284e+05,"(36.69197, -98.04989)",5161.563343
127,83.175427,66.846883,2014-08-18 08:59:24.131434,2.742310e+05,"(83.1754270867, 66.8468830279)",1053.353765
133,35.924453,-98.143570,2014-08-17 21:01:48.201650,1.972001e+05,"(35.924453, -98.14357)",5214.734000
135,36.624503,-98.115210,2014-08-18 05:31:39.685119,5.542105e+05,"(36.624503, -98.11521)",5166.602676
141,35.843380,-97.899200,2014-08-17 17:53:02.775032,4.004123e+04,"(35.84338, -97.8992)",5218.706591
146,36.665515,-97.951310,2014-08-20 08:59:12.496809,2.350955e+05,"(36.665515, -97.95131)",5162.741325
149,36.207110,-98.650750,2014-08-21 19:40:55.995454,4.929208e+05,"(36.20711, -98.65075)",5198.574466
161,36.628543,-97.884060,2014-08-19 04:24:34.295584,5.006745e+05,"(36.628543, -97.88406)",5164.838794
168,36.598050,-98.000194,2014-08-20 15:18:19.184932,2.317813e+05,"(36.59805, -98.000194)",5167.676870
...,...,...,...,...,...,...
88002,36.627800,-97.981060,2014-11-18 10:59:08.385178,4.578091e+05,"(36.6278, -97.98106)",5165.516116
88003,36.414600,-98.246845,2015-03-11 02:12:19.061488,3.556320e+05,"(36.4146, -98.246845)",5181.819818
88006,36.192980,-97.721996,2015-03-03 18:59:16.424881,1.339722e+05,"(36.19298, -97.721996)",5193.609381
88008,36.607276,-98.043670,2014-10-09 17:44:17.610685,4.477835e+05,"(36.607276, -98.04367)",5167.324388
88009,36.601080,-98.035310,2014-10-01 06:45:42.893920,4.020201e+05,"(36.60108, -98.03531)",5167.695091
88010,36.520083,-98.217470,2015-01-16 13:36:24.804729,2.358556e+05,"(36.520083, -98.21747)",5174.407332
88011,36.610785,-98.026165,2014-11-16 16:10:29.146272,1.008267e+08,"(36.610785, -98.026165)",5166.971633
88012,36.577857,-98.004620,2014-12-19 20:11:26.797733,2.527765e+05,"(36.577857, -98.00462)",5169.088374
88013,36.469157,-98.241150,2014-12-24 17:20:19.403862,3.313529e+05,"(36.469157, -98.24115)",5178.046375
88014,36.477620,-98.270720,2014-10-04 13:50:38.486131,1.769109e+05,"(36.47762, -98.27072)",5177.654366
88016,36.659750,-98.154870,2015-01-14 01:58:27.440311,2.572263e+05,"(36.65975, -98.15487)",5164.441524
88017,36.635604,-98.147830,2015-02-20 02:09:31.848501,5.062269e+05,"(36.635604, -98.14783)",5166.050590
88018,36.610053,-98.014370,2015-01-24 01:44:20.740556,3.877357e+05,"(36.610053, -98.01437)",5166.945960
88019,36.569716,-98.175426,2014-12-23 10:17:38.755321,3.129155e+05,"(36.569716, -98.175426)",5170.739791
88021,36.271493,-173.369994,2015-02-08 17:58:51.561571,1.195840e+05,"(36.2714934868, -173.369994473)",4649.587182
88022,36.309066,-98.049230,2015-11-26 04:56:38.516394,3.549200e+05,"(36.309066, -98.04923)",5187.785009
88024,36.272080,-98.644280,2014-11-16 10:33:47.444821,7.511696e+05,"(36.27208, -98.64428)",5194.082431
88025,36.312163,-98.050060,2015-05-25 09:33:45.391206,1.600815e+05,"(36.312163, -98.05006)",5187.578232
88026,36.388570,-98.679370,2014-12-03 01:19:48.123516,1.365750e+05,"(36.38857, -98.67937)",5186.318103
88028,-13.681511,70.247474,2014-10-05 21:29:20.805497,6.514982e+05,"(-13.6815111369, 70.2474739891)",5635.527209
88029,36.193286,-98.568386,2015-08-16 00:33:36.559011,1.363689e+05,"(36.193286, -98.568386)",5199.008239
88030,36.495240,-98.157210,2014-12-28 17:59:39.558289,1.594096e+05,"(36.49524, -98.15721)",5175.725095
88031,36.486255,-97.606610,2015-05-28 19:00:53.987373,1.136159e+05,"(36.486255, -97.60661)",5172.770472
88032,36.409430,-98.489635,2015-06-26 10:58:01.968119,5.699191e+05,"(36.40943, -98.489635)",5183.706228
88033,36.450522,-98.231914,2015-03-01 21:09:51.127320,6.335257e+05,"(36.450522, -98.231914)",5179.264194
88034,36.715210,-97.991270,2015-05-31 18:52:08.144573,4.368070e+05,"(36.71521, -97.99127)",5159.595119
88036,36.704966,-98.158280,2015-08-26 16:32:40.090264,2.427810e+05,"(36.704966, -98.15828)",5161.366008
88037,36.212090,-98.058780,2014-09-16 10:56:59.521584,2.936446e+04,"(36.21209, -98.05878)",5194.488394
88039,36.498835,-97.882366,2015-02-21 15:48:06.541742,2.372660e+05,"(36.498835, -97.882366)",5173.710717
88041,36.130510,-98.222950,2015-01-05 18:41:34.073452,1.684704e+05,"(36.13051, -98.22295)",5201.127880